### ISSUE TITLE
Default network functionality

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/multus-cni#2]
The spec calls for:

> The meta-plugin must always attach the pod to the cluster-wide default network, keeping the existing Kubernetes behavior.  This behavior currently consists of selecting the UTF-8 alphabetically first (via Go’s strings.Sort() on filenames ) valid CNI .conf or .conflist file in /etc/cni/net.d.

Currently Multus uses the `delegates:` field in the configuration in order to specify the default network.

Tomo mentioned that we should potentially change the name to something that is less confusing than "delegates" maybe. Potentially `default_configuration:` could be more intuitive.

**Comment by s1061123** [comment]
@dougbtv , thank you for filing the issue! and let me add more comment in it.

I've read the spec again. This spec defines we just put 'default network CNI' in /etc/cni/net.d, so the spec assume that kubernetes support mutliple interface by itself, I guess.

Currently k8s does not support multiple interface and we need to use multus, so we may provide a transitional way to define 'default network' in feasible way.

**Comment by s1061123** [comment]
In addition, we may clarify that whether default network should be add or not implicitly for following case:

**case1: empty network in pod yaml**
```
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
  annotations:
    kubernetes.cni.cncf.io/v1/networks: |
      [
      ]
```

**case2: no default network annotations in pod yaml**
```
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
  annotations:
    kubernetes.cni.cncf.io/v1/networks: non-default-net1, non-default-net2
```
