### ISSUE TITLE
Detecting JSON vs. incorrectly formatted JSON vs. detecting CSV

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/multus-cni#8]
Initial "detection" of CSV only assumes that if you can't parse JSON -- it must be CSV. 

Potentially, we could look at the formats of CSV vs. JSON, and then give an error message on bad JSON, or, bad CSV. 

See some remarks in PR #5

**Comment by dougbtv** [comment]
```
[centos@kube-master ~]$ cat comma.bothpod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes.cni.cncf.io/networks: macvlan-conf,flannel-conf
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
[centos@kube-master ~]$ cat bothpod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes.cni.cncf.io/networks: '[  
        { "name": "flannel-conf" },
        { "name": "macvlan-conf" }
    ]'
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
[centos@kube-master ~]$ cat bad.json.bothpod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: bothpod
  annotations:
    kubernetes.cni.cncf.io/networks: '[  
        { "name": "flannel-conf" },asdf
        { "name": "macvlan-conf" }
    ]'
spec:
  containers:
  - name: bothpod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80

```
